services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  Waldhacker\Plausibleio\:
    resource: '../Classes/*'

  Waldhacker\Plausibleio\Controller\VisitorTimeSeriesController:
    public: true

  waldhacker.plausibleio.widget.country:
    class: 'Waldhacker\Plausibleio\Dashboard\Widget\CountryDataWidget'
    arguments:
      $dataProvider: '@Waldhacker\Plausibleio\Dashboard\DataProvider\CountryDataProvider'
      $view: '@dashboard.views.widget'
      $configurationService: '@Waldhacker\Plausibleio\Services\ConfigurationService'
      $options:
        siteId: null
        timeFrame: 7d
    tags:
      - name: dashboard.widget
        identifier: 'plausible.countrydata'
        groupNames: 'plausibleio'
        title: 'LLL:EXT:plausibleio/Resources/Private/Language/locallang.xlf:widgets.countryData.label'
        description: 'LLL:EXT:plausibleio/Resources/Private/Language/locallang.xlf:widgets.countryData.description'
        iconIdentifier: 'content-widget-chart-bar'
        height: 'medium'
        width: 'medium'

  waldhacker.plausibleio.widget.page:
    class: 'Waldhacker\Plausibleio\Dashboard\Widget\PageDataWidget'
    arguments:
      $dataProvider: '@Waldhacker\Plausibleio\Dashboard\DataProvider\PageDataProvider'
      $view: '@dashboard.views.widget'
      $configurationService: '@Waldhacker\Plausibleio\Services\ConfigurationService'
      $options:
        siteId: null
        timeFrame: 7d
    tags:
      - name: dashboard.widget
        identifier: 'plausible.pagedata'
        groupNames: 'plausibleio'
        title: 'LLL:EXT:plausibleio/Resources/Private/Language/locallang.xlf:widgets.pageData.label'
        description: 'LLL:EXT:plausibleio/Resources/Private/Language/locallang.xlf:widgets.pageData.description'
        iconIdentifier: 'content-widget-chart-bar'
        height: 'medium'
        width: 'medium'

  waldhacker.plausibleio.widget.visitorsovertime:
    class: 'Waldhacker\Plausibleio\Dashboard\Widget\VisitorsOverTime'
    arguments:
      $dataProvider: '@Waldhacker\Plausibleio\Dashboard\DataProvider\TimeSeriesDataProvider'
      $view: '@dashboard.views.widget'
      $configurationService: '@Waldhacker\Plausibleio\Services\ConfigurationService'
      $options:
        siteId: null
    tags:
      - name: dashboard.widget
        identifier: 'plausible.visitorsovertime'
        groupNames: 'plausibleio'
        title: 'LLL:EXT:plausibleio/Resources/Private/Language/locallang.xlf:widgets.visitorsOverTime.label'
        description: 'LLL:EXT:plausibleio/Resources/Private/Language/locallang.xlf:widgets.visitorsOverTime.description'
        iconIdentifier: 'content-widget-chart-bar'
        height: 'large'
        width: 'medium'

  waldhacker.plausibleio.widget.browser:
    class: 'Waldhacker\Plausibleio\Dashboard\Widget\BrowserDataWidget'
    arguments:
      $dataProvider: '@Waldhacker\Plausibleio\Dashboard\DataProvider\BrowserDataProvider'
      $view: '@dashboard.views.widget'
      $configurationService: '@Waldhacker\Plausibleio\Services\ConfigurationService'
      $options:
        siteId: null
        timeFrame: 7d
    tags:
      - name: dashboard.widget
        identifier: 'plausible.browserdata'
        groupNames: 'plausibleio'
        title: 'LLL:EXT:plausibleio/Resources/Private/Language/locallang.xlf:widgets.browserData.label'
        description: 'LLL:EXT:plausibleio/Resources/Private/Language/locallang.xlf:widgets.browserData.description'
        iconIdentifier: 'content-widget-chart-bar'
        height: 'medium'
        width: 'medium'


  waldhacker.plausibleio.widget.device:
    class: 'Waldhacker\Plausibleio\Dashboard\Widget\DeviceDataWidget'
    arguments:
      $dataProvider: '@Waldhacker\Plausibleio\Dashboard\DataProvider\DeviceDataProvider'
      $view: '@dashboard.views.widget'
      $configurationService: '@Waldhacker\Plausibleio\Services\ConfigurationService'
      $options:
        siteId: null
        timeFrame: 7d
    tags:
      - name: dashboard.widget
        identifier: 'plausible.devicedata'
        groupNames: 'plausibleio'
        title: 'LLL:EXT:plausibleio/Resources/Private/Language/locallang.xlf:widgets.deviceData.label'
        description: 'LLL:EXT:plausibleio/Resources/Private/Language/locallang.xlf:widgets.deviceData.description'
        iconIdentifier: 'content-widget-chart-bar'
        height: 'medium'
        width: 'medium'


